import type { Metadata } from "next";
import { Ysabeau_Infant } from "next/font/google";
import "./globals.css";

const ysabeauInfant = Ysabeau_Infant({
  variable: "--font-ysabeau",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ysabeauInfant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
